### PR TITLE
Fix indentation and formatter 

### PR DESCRIPTION
**Pull request by foges**
Issues with the current implementation, which this PR fixes:

Indentation
 - The increase and decrease indent regexes were swapped.
 - The comment syntax was incorrect (previously `//` and `/* */` -- now `#`)
 - By using indentationRules rather than onEnterRules it wasn't possible to indent based on the cursor position, which meant that `(def a <Enter>)` (def a) <Enter>` were treated the same. Now you'll get an indent if a line only has an opening brace.
 - Indentation was different for `[` `(` `{` which seemed unintuitive to me, since you'd expect all of them to add an indent.
 - Comments after opening braces were previously not supported, which they now are.

Formatter:
 - When running the formatter janet complains that `)(` is invalid syntax. Adding a space fixes this.

For anyone that's interested this is a guide to how the configuration.json file works: https://code.visualstudio.com/api/language-extensions/language-configuration-guide

### CODE REVIEW

**Comment by sogaiu** [comment]
> When running the formatter janet complains that )( is invalid syntax. Adding a space fixes this.

I wonder if that is platform-specific somehow as I don't see that problem here.  Having said that, an extra space doesn't seem harmful.  The failure is odd though.

What I did to test was to invoke `> Janet: Format file` from the command palette.  The terminal opened and I could see execution completing:

```
$ janet -s
Janet 1.26.1-dev-746ff530 linux/x64/gcc - '(doc)' for help
repl:1:> (import spork/fmt)(fmt/format-file "/home/user/test.janet")
@{_ @{:value <cycle 0>} fmt/format @{:private true} fmt/format-file @{:private true} fmt/format-print @{:private true} :macro-lints @[]}
nil
```

Probably one can tell by looking at the output, but FWIW this is on a Llinux box.

**Comment by sogaiu** [comment]
Thanks for the link -- nice to have a reference.

**Comment by sogaiu** [comment]
I've only tested briefly, but so far I can see the changes seem to handle certain situations better :+1: 

As a concrete example, I tried to enter a simple form [here](https://github.com/CFiggers/joule-editor/blob/60d258c34e43b44ccfd2be3e2db3e6b349b90bfb/src/syntax-highlights.janet#L32).

With fdae1696c1c08017a557f3d9d69b1d9d454bac02 (latest commit on current default branch) pressing enter (with the cursor at the aforementioned line) leads to unwanted indentation.

With 78a189730cbc4c3f65ffd1f72154e4128addd8d0 (latest commit in this PR), the behavior is better (i,e, no unwanted indentation).

---

A minor thing I noticed -- for a blank file (after setting the language to Janet via the UI at the bottom of the window), I get indentation like the following for the arguments of a `defn`:
```
(defn a
    [x])
```

The unexpected bit here is the > 2 spaces.

I don't know if that's a big deal as using `Janet: Format file` will reduce whitespace (assuming the file has been saved).

Also I don't see the same behavior when editing an existing file and may be that's a much more likely scenario.

---

On a side note, switching between different versions of the extension seems to be doable via the combination of symlink (re)creation and removal of `extensions.json` (plus restarting VSCode).

**Comment by foges** [comment]
Thank you for testing @sogaiu

**Comment by sogaiu** [comment]
Thanks for your efforts @foges :)

**Pull request merged**
